# Generated by Django 5.1.5 on 2025-01-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=100, verbose_name='Name 1')),
                ('name2', models.CharField(max_length=100, verbose_name='Name 2')),
            ],
        ),
    ]
